-- color scheme
vim.api.nvim_command("hi! Normal gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi! Visual gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi! Comment gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi! Search gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi EndOfBuffer guifg=NONE guibg=NONE ctermbg=NONE ctermfg=NONE")
vim.api.nvim_set_option("background", "dark")
vim.api.nvim_command("colorscheme catppuccin")
vim.api.nvim_command("hi clear LineNr")
vim.api.nvim_command("hi clear SignColumn")
vim.api.nvim_command("hi! link markdownItalic Italic")
vim.api.nvim_command("hi! link markdownBold Bold")
vim.api.nvim_command("hi! WinSeparator ctermbg=NONE ctermfg=DarkGrey guibg=NONE guifg=#0791D1")
vim.api.nvim_command("hi! Comment ctermbg=DarkGrey ctermfg=Black cterm=bold guifg=#606060 guibg=NONE")
vim.api.nvim_command("hi! Search ctermbg=DarkGrey ctermfg=Black cterm=bold guifg=#CCCCDD guibg=#5775E4")
vim.api.nvim_command("hi! CurSearch ctermbg=DarkGrey ctermfg=Black cterm=bold guifg=#CCCCDD guibg=#00AAAA")
vim.api.nvim_command("hi! Visual ctermbg=DarkGrey ctermfg=NONE cterm=bold guifg=NONE guibg=#243E9F")
vim.api.nvim_command("hi! Colorcolumn ctermbg=Grey cterm=bold guibg=#303030")
vim.api.nvim_command("hi! Cursorline ctermbg=Grey cterm=bold guibg=#303030")
vim.api.nvim_command("hi! Cursorcolumn ctermbg=Grey cterm=bold guibg=#303030")
vim.api.nvim_command("hi! HighlightedyankRegion ctermfg=Black ctermbg=Yellow cterm=bold guifg=#000000 guibg=#9CE342")
vim.api.nvim_command("hi clear SpellBad")
vim.api.nvim_command("hi clear SpellCap")
vim.api.nvim_command("hi clear SpellRare")
vim.api.nvim_command("hi! SpellBad cterm=undercurl ctermfg=LightRed guisp=LightRed gui=undercurl guifg=LightRed")
vim.api.nvim_command("hi! SpellCap cterm=undercurl ctermfg=LightRed guisp=LightRed gui=undercurl guifg=LightRed")
vim.api.nvim_command("hi! SpellRare cterm=undercurl ctermfg=LightRed guisp=LightRed gui=undercurl guifg=LightRed")

--mini.tabline
vim.api.nvim_set_hl(0, "MiniTablineVisible", { fg = "#606070", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniTablineCurrent", { fg = "#00DDDD", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniTablineModifiedVisible", { fg = "#976300", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniTablineModifiedHidden", { fg = "#8E5D00", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniTablineModifiedCurrent", { fg = "#DD9100", bg = "#202020" })

--mini.statusline
vim.api.nvim_set_hl(0, "MiniStatuslineModeNormal", { fg = "#50DD6A", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineModeInsert", { fg = "#5080DD", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineModeVisual", { fg = "#DD00DD", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineModeReplace", { fg = "#DD4040", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineModeCommand", { fg = "#CCCCDD", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineFilename", { fg = "#CCCCDD", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineFileinfo", { fg = "#CCCCDD", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineDiagnostics", { fg = "#DD4040", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineGit", { fg = "#50DD6A", bg = "#202020" })
vim.api.nvim_set_hl(0, "MiniStatuslineLocation", { fg = "#CCCCDD", bg = "#202020" })
