-- color scheme
vim.api.nvim_command("hi! Normal gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi! Visual gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi! Search gui=NONE guifg=NONE guibg=NONE cterm=NONE ctermfg=NONE ctermbg=NONE")
vim.api.nvim_command("hi EndOfBuffer guifg=NONE guibg=NONE ctermbg=NONE ctermfg=NONE")
vim.api.nvim_set_option("background", "dark")
vim.api.nvim_command("colorscheme default")
vim.api.nvim_command("hi clear LineNr")
vim.api.nvim_command("hi clear SignColumn")
vim.api.nvim_command("hi! link markdownItalic Italic")
vim.api.nvim_command("hi! link markdownBold Bold")
vim.api.nvim_command("hi! WinSeparator ctermbg=NONE ctermfg=DarkGrey guibg=NONE guifg=#0791D1")
vim.api.nvim_command("hi! Search ctermbg=DarkGrey ctermfg=Black cterm=bold guifg=#CCCCDD guibg=#455AAA")
vim.api.nvim_command("hi! CurSearch ctermbg=DarkGrey ctermfg=Black cterm=bold guifg=#CCCCDD guibg=#00AAAA")
vim.api.nvim_command("hi! Visual ctermbg=DarkGrey ctermfg=NONE cterm=bold guifg=NONE guibg=#455AAA")
vim.api.nvim_command("hi! Colorcolumn ctermbg=Grey cterm=bold guibg=#303030")
vim.api.nvim_command("hi! Cursorline ctermbg=Grey cterm=bold guibg=#303030")
vim.api.nvim_command("hi! Cursorcolumn ctermbg=Grey cterm=bold guibg=#303030")
vim.api.nvim_command("hi! HighlightedyankRegion ctermfg=Black ctermbg=Yellow cterm=bold guifg=#000000 guibg=#9CE342")
vim.api.nvim_command("hi clear SpellBad")
vim.api.nvim_command("hi clear SpellCap")
vim.api.nvim_command("hi clear SpellRare")
vim.api.nvim_command("hi SpellBad cterm=undercurl guisp=Red gui=undercurl")
vim.api.nvim_command("hi SpellCap cterm=undercurl guisp=Yellow gui=undercurl")
vim.api.nvim_command("hi SpellRare cterm=undercurl guisp=Blue gui=undercurl")
